marquez:
  enabled: true

#  port: 80
#
#  hostname: marquez.playground-ns.svc.cluster.local

  postgresql:
    enabled: true

airflow:
  enabled: true

  postgresql:
    enabled: true

  workers:
    persistence:
      # Enable persistent volumes
      enabled: true # this is the default (true)
      # Volume size for worker StatefulSet
      size: 20Gi
