apiVersion: batch/v1
kind: Job
metadata:
  name: dbinit
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: marquezdb
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h","playground-postgresql.playground-ns.svc.cluster.local", "-U", "postgres", "marquez" ]
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: playground-postgresql
              key: postgres-password
      - name: airflowdb
        image: bitnami/postgresql:latest
        command: ["createdb"]
        args: ["-h","playground-postgresql.playground-ns.svc.cluster.local", "-U", "postgres", "airflow" ]
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: playground-postgresql
              key: postgres-password
      restartPolicy: Never